# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "/engcomputaria.github.io" # repository name
url: "https://engcomputaria.github.io" # Either custom domain or http://GithubUsername.github.io

# Podcast Feed Settings
title:          "Engenhação da Computaria" # name of your podcast
email:          engdacomputaria@gmail.com # CHANGE
description:    "Podcast feito por um aluno de engenharia da computação sobre assuntos de tecnologia" # CHANGE
subtitle:       "Engenharia da Computação nua e crua!" # CHANGE
lang:           en-us
author:         Calebe94 # CHANGE
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: Brazil/Sao_Paulo #CHANGE

# Basic

# Navigation
nav:
  - name:           "About"
    href:           "/microcast/about" # CHANGE "microcast" to match your repository
  - name:           "Feed"
    href:           "/microcast/podcast.rss" # CHANGE "microcast" to match your repository
  - name:           "iTunes"
    href:           "https://itunes.apple.com/us/podcast/driftwood/id1080157963" #CHANGE
  - name:           "Overcast"
    href:           "https://overcast.fm/itunes1080157963/driftwood" # CHANGE

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
