# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
baseurl: "" # repository name
url: "https://engcomputaria.github.io" # Either custom domain or http://GithubUsername.github.io

# Podcast Feed Settings
title:          "Engenhação da Computaria" # name of your podcast
email:          engdacomputaria@gmail.com # CHANGE
description:    "Podcast feito por um aluno de engenharia da computação sobre assuntos de tecnologia" # CHANGE
subtitle:       "Engenharia da Computação crua e BEM nua!" # CHANGE
lang:           en-us
author:         Calebe94 # CHANGE
copyright:      "&#x2117; &amp; &#xA9; 2016"


# Outputting
permalink: /:title/

# Build settings
markdown: kramdown
timezone: Brazil/Sao_Paulo #CHANGE

# Basic

# Navigation
nav:
  - name:           "Sobre"
    href:           "/about" # CHANGE "microcast" to match your repository
    
  - name:           "Feed"
    href:           "/podcast.rss" # CHANGE "microcast" to match your repository
  
  - name:           "Anchor"
    href:           "http://anchor.fm/engcomputaria"

  - name:           "Spotify"
    href:           "https://open.spotify.com/show/0ku0pRGk0FM5ImyZojaYic"

  - name:           "Google Podcasts"
    href:           "https://www.google.com/podcasts?feed=aHR0cHM6Ly9hbmNob3IuZm0vcy85MWE5OTM0L3BvZGNhc3QvcnNz"

  - name:           "SoundCloud"
    href:           "https://soundcloud.com/engenhacao-da-computaria" # CHANGE
  
  - name:           "Pocket Casts"
    href:           "https://pca.st/ILxL"
  
  - name:           "Breaker"
    href:           "https://www.breaker.audio/engenhacao-da-computaria"
  
  - name:           "Radio Public"
    href:           "https://radiopublic.com/engenhao-da-computaria-GyZgNZ"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
